name: Generate Apks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Chmod Gradle
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew build

      - name: Assemble Debug Apk
        run: ./gradlew assembleDebug

      - name: Assemble Release Apk
        run: ./gradlew assembleRelease

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: ./app/build/outputs/apk/debug/*.apk

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./app/build/outputs/apk/release/*.apk

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: apks